### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by forconz** [jiesutd/YEDDA#10]
git clone https://github.com/jiesutd/YEDDA.git
python YEDDA_Annotator.py
it throw a error.

PS D:\Projects\Test\Information-Extraction-Chinese\YEDDA> python YEDDA_Annotator.py
  File "YEDDA_Annotator.py", line 185
    print "Action Track: singleLeftClick"
                                        ^
**SyntaxError: Missing parentheses in call to 'print'**

**Comment by forconz** [comment]
跑YEDDA-0.6> python SUTDAnnotator.py也是这个问题

**Comment by chinmayshah99** [comment]
Hey @forconz, it's due to different version of python. You can check it [here](https://stackoverflow.com/questions/1093322/how-do-i-check-what-version-of-python-is-running-my-script).
You need  python 2.x for this repo.

**Comment by forconz** [comment]
@chinmayshah99 many thanks
