### ISSUE TITLE
如何增加新的实体类别

### ISSUE THREAD

**Issue by caizhuo** [jiesutd/YEDDA#16]
请问如何新增实体类别，8个类别有点不够用

**Comment by jiesutd** [comment]
Just add your classes here: https://github.com/jiesutd/YEDDA/blob/ac03bb15beed3206420f4be55d060e7730325d25/YEDDA_Annotator.py#L34

Please avoid some key shortcuts, i.e. `q`, `y`.

**Comment by caizhuo** [comment]
thanks

**Comment by gui-li** [comment]
Nothing changed in the GUI after I changed self.pressCommand dictionary in  YEDDA.py

**Comment by jiesutd** [comment]
@gui-li after you change the dictionary, you need to close the old one and rerun the code.

**Comment by gui-li** [comment]
> @gui-li after you change the dictionary, you need to close the old one and rerun the code.

I am sure I did save the py file and rerun it, but it didn't take effect.
![Annotation 2019-07-31 103315](https://user-images.githubusercontent.com/23182403/62220918-d4dcc480-b37e-11e9-8c75-df0311085ecf.jpg)
![Annotation 2019-07-31 103329](https://user-images.githubusercontent.com/23182403/62220933-da3a0f00-b37e-11e9-98a9-233e43c7a6dd.jpg)

**Comment by jiesutd** [comment]
@gui-li  send me the updated code and I will see what happened. jieynlp@gmail.com
