### ISSUE TITLE
Increase the number of map labels

### ISSUE THREAD

**Issue by anandpratapsingh25** [jiesutd/YEDDA#18]
Is there any option to increase number shortcut map labels

**Comment by jiesutd** [comment]
@anandpratapsingh25  Yes, you can change the below code to add more shortcuts. Please avoid function key `y` `q`. 

https://github.com/jiesutd/YEDDA/blob/ac03bb15beed3206420f4be55d060e7730325d25/YEDDA_Annotator.py#L34
