### ISSUE TITLE
How many labels can i add at most?

### ISSUE THREAD

**Issue by ares5221** [jiesutd/YEDDA#22]
How many labels can i add at most?

**Comment by jiesutd** [comment]
You can add more than 20 labels in the most direct way. (all `a-z` alphabet except `q` and `y`). You can use even more labels by using different config files.

**Comment by ares5221** [comment]
> You can add more than 20 labels in the most direct way. (all `a-z` alphabet except `q` and `y`). You can use even more labels by using different config files.

ok， thank you
