### ISSUE TITLE
[question]bugs on MacOS

### ISSUE THREAD

**Issue by buptzcW** [jiesutd/YEDDA#23]
hi @jiesutd ,when i use YEDDA on MacOS ,i can not load data into it, it just dosent response at all. can you help me out? thanks

**Comment by jiesutd** [comment]
It works ok in my MacOS system. Please show me your UI and the file you loaded.

**Comment by buptzcW** [comment]
this is a part of my data, and the pics were captured when i loaded the part of data.  the first pic shows that YEDDA didnt response when i load the data, the second pic came up after the first pic 
[validation_30.csv.zip](https://github.com/jiesutd/YEDDA/files/3465925/validation_30.csv.zip)
<img width="1575" alt="WeChat5655891555dc26afcf4929a4c9d2c420" src="https://user-images.githubusercontent.com/33115565/62438972-76e41e80-b77c-11e9-81ed-3ba25c9d76fb.png">
<img width="500" alt="WeChat4287f265b438ae9012a85c955acef345" src="https://user-images.githubusercontent.com/33115565/62438930-413f3580-b77c-11e9-8217-5349564a344a.png">

**Comment by jiesutd** [comment]
It does not support the .csv file format. It only support txt file. As I said in the readme file:

`Click Open button and select your input file. (You may set your file name ended with .txt or .ann if possible)`

**Comment by buptzcW** [comment]
i tried the .txt file, it doesnt work either

**Comment by jiesutd** [comment]
Send me a copy

**Comment by buptzcW** [comment]
[validation_30.txt.zip](https://github.com/jiesutd/YEDDA/files/3465956/validation_30.txt.zip)

**Comment by buptzcW** [comment]
i use Pandas to transform data from csv to txt

**Comment by jiesutd** [comment]
Yes, I can reimplement your report. It is actually a weird Apple OSX bug: https://github.com/sqweek/dialog/issues/24 

The problem may be the OSX has some bug when loading the file containing the emoji text. 

Solution: If you remove the emoji (third sentences in your txt file), then YEDDA can work.

**Comment by buptzcW** [comment]
thanks a lot,! your solution is perfect, i just transform the emoji to str with PYPI emoji, and now it works!
