### ISSUE TITLE
 Pairwise Annotators Comparison

### ISSUE THREAD

**Issue by baijingetangzichen** [jiesutd/YEDDA#25]
According to the demotext/UserA.ann and demotext/UserB.ann provided, using the Pairwise Annotators Comparison function, there will be errors or PDF documents can not be opened.
![image](https://user-images.githubusercontent.com/29220807/62677441-e65a4800-b9e0-11e9-9480-b0fc94323115.png)

Windows 10 System、python2.7.15

**Comment by jiesutd** [comment]
The pairwise annotation requires the two annotations have the same context. This error may be caused by the context that has been modified in some annotation. Could you please send me the two annotations you tested?
