### ISSUE TITLE
support python 3 version ?

### ISSUE THREAD

**Issue by yanyusong** [jiesutd/YEDDA#30]
Could you please provide a version for python3 ?

**Comment by Freeshman** [comment]
I modified the YEDDA.py file and changed the way of storing the config file, maybe you can have a try:)
Thanks Jie Yang.

**Comment by rickyhuw** [comment]
did it work?

**Comment by jiesutd** [comment]
We have updated YEDDA and now it supports Python 3.

**Comment by rickyhuw** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，您的邮件已被接受，我将尽快回复您！
