### ISSUE TITLE
YEDDA怎么标注实体关系？

### ISSUE THREAD

**Issue by tanzf** [jiesutd/YEDDA#34]
请问YEDDA能够标注实体关系吗？能的话怎么标注实体关系？求指导，谢谢

**Comment by jiesutd** [comment]
暂不支持关系标注，谢谢

**Comment by jtyoui** [comment]
> 请问YEDDA能够标注实体关系吗？能的话怎么标注实体关系？求指导，谢谢

我也有这种需求
