### ISSUE TITLE
你好，工具很好用，问下不同实体不同颜色可以实现吗，哪里可以控制颜色

### ISSUE THREAD

**Issue by hantaozi** [jiesutd/YEDDA#35]

**Comment by baotongnoob** [comment]
> _No description provided._

为什么我选中按A 直接就相当于往里面打字了

**Comment by jiesutd** [comment]
We just updated YEDDA. The new version supports customizing colors based on entity types.

**Comment by Heduang** [comment]
你好。我已经收到您的邮件。
