### ISSUE TITLE
[Suggestion] Add export settings as buttons on GUI

### ISSUE THREAD

**Issue by jinangela** [jiesutd/YEDDA#7]
Hi jiesutd, thank you for building this wonderful tool! A little suggestion here: could you add export settings as some buttons on the GUI so that users don't need to go inside the code, modify it then rerun the program? I think that way it would be more user-friendly.

**Comment by jiesutd** [comment]
Hi @jinangela , that's a good idea. Will consider to add this function when I am free.

**Comment by jiesutd** [comment]
We have updated YEDDA and added the export GUI.
